config/routes.rb
Rails.application.routes.draw do
  get 'courses/', to: 'courses#index'
  get 'courses/new'
  get 'courses/:id', to: 'courses#show', as: 'show_course'
  post 'courses/', to: 'courses#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
# == Schema Information
#
# Table name: courses
#
#  id          :integer          not null, primary key
#  title       :string
#  description :string
#  published   :boolean          default(FALSE)
#  visible     :boolean          default(FALSE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Course < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.where(visible: true)
  end

  def new
    @course = Course.new
  end

  def create
    # @course = Course.create title:params[:course][:title], description:params[:course][:description], visible:params[:course][:visible]
    @course = Course.create course_params
    redirect_to courses_path
  end
  def show
    @course = Course.find params[:id]
  end

  private
  def course_params
    params.required(:course).permit(:title, :description, :visible, :published)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/index.html.erb
<%= link_to "Home", "/courses/"%>
<%= link_to "New", "/courses/new"%>
<h1>Índice de Cursos</h1>

<ul>
  <% @courses.each do |course| %>
    <li>
      <%= link_to course.title, show_course_path(id: course.id) %>
    </li>
  <% end %>
</ul>

app/views/courses/new.html.erb
<%= link_to "Home", "/courses/"%>
<%= form_with model: @course do |f| %>
  <div>
    <%= f.label 'Título: ' %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label 'Descripción: '%>
    <%= f.text_area :description, placeholder: 'Describe el curso' %>
  </div>
  <div>
    <%= f.label 'Visible: '%>
    <%= f.check_box :visible %>
  </div>
  <div>
    <%= f.label 'Publicado: '%>
    <%= f.check_box :published %>
  </div>
  <%= f.submit "Crear curso" %>
<% end %>

app/views/courses/show.html.erb
<%= link_to "Home", "/courses/"%>
<h2>
  <%= @course.title %>
</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>